### ISSUE TITLE
Stanford link for UNIX info is dated

### ISSUE THREAD

**Issue by sethwoodworth** [omarduarte/juniors_should_know#6]
http://doors.stanford.edu/~sr/computing/basic-unix.html

Suggests `lpr` for printing from the command line, as well as a series of commands about multi-user unix machines (`who`, `finger`) that are unlikely to be used by modern developers in virtual machines.

I don't have a better suggestion off of the top of my head, but if someone is looking to replace something on this list, this would be a good target.

**Comment by omarduarte** [comment]
Getting this in instead:
http://www.thegeekstuff.com/2010/11/50-linux-commands/

Thanks a lot!
